id: A41EB614D
title: CI_Verses 21-40
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:01:29.218925
  last_modified_at: 2022-03-01 23:01:29.218936
