id: A41EB614D
title: Colophon
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:01:29.524944
  last_modified_at: 2022-03-01 23:01:29.524947
