id: A41EB614D
title: Chapter XX-XXI
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:01:29.521116
  last_modified_at: 2022-03-01 23:01:29.521122
